twig:
    file_name_pattern: '*.twig'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]

    paths:
        # directories are relative to the project root dir (but you
        # can also use absolute directories)
        '%kernel.project_dir%/src/UserBundle/Templates': 'UserBundle'
        '%kernel.project_dir%/src/CoreBundle/Templates': 'CoreBundle'
        '%kernel.project_dir%/src/ExcursionBundle/Templates': 'ExcursionBundle'

when@test:
    twig:
        strict_variables: true