services:
  app:
    image: ghcr.io/gabrielroot/mytour-app:latest
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - symfony_app_var:/var/www/var
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - symfony_app

  nginx:
    image: ghcr.io/gabrielroot/mytour-nginx:latest
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - symfony_app
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Accept: text/html", "http://localhost/login/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - app

volumes:
  symfony_app_var:

networks:
  symfony_app:
