server {
    listen 80;
    server_name mytour.grwxtech.com;
    index index.php index.html;

    error_log /var/log/nginx/auth_error.log;
    access_log /var/log/nginx/auth_access.log;

    root /var/www/public;

    client_max_body_size 1G;

    # Docker DNS resolver
    resolver 127.0.0.11 valid=30s ipv6=off;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ ^/.+\.php(/|$) {
        # Use variable to force runtime DNS resolution
        set $upstream mytour_app:9000;
        fastcgi_pass $upstream;
        include fastcgi_params;
        fastcgi_read_timeout 600;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /stub_status {
        stub_status;
        allow 127.0.0.1;
        allow 10.200.0.0/24;
        deny all;
    }
}
