my_tour.core.bundle:
    resource: '../src/CoreBundle/config/routing.yml'

my_tour.user.bundle:
    resource: '../src/UserBundle/config/routing.yml'

my_tour.excursion.bundle:
    resource: '../src/ExcursionBundle/config/routing.yml'
